- name: Publish Dart/Flutter package
  # You may pin to the exact commit or the version.
  # uses: sakebook/actions-flutter-pub-publisher@ccd9fbba502ea7ef33ea2479e0cdac5a2a9766e1
  uses: sakebook/actions-flutter-pub-publisher@v1.4.1
  with:
    # Google Account credential
    credential: 
    # (Optional) Publish packages type. (default: true)
    flutter_package: # optional, default is true
    # (Optional) Skip test (default: false)
    skip_test: # optional
    # (Optional) Package directory (default: ".")
    package_directory: # optional, default is .
    # (Optional) Dry run, no publish (default: false)
    dry_run: # optional
