name: flutter_exposure
description: A Flutter scrollable widget buried exposure tool.
version: 0.0.4
homepage: https://github.com/Vadaski/flutter_exposure/

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
